name: YouTube Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -U yt-dlp

      - run: |
          yt-dlp \
          --extractor-args "youtube:player_client=android_vr,tv" \
          -j "https://youtu.be/-6a9RSBeADw"
